ServerName localhost
<VirtualHost *:80>
    ServerName pdfraktor.localhost
    ServerAlias www.pdfraktor.fr

    DocumentRoot /var/www/project/public

    <Directory /var/www/project/public>
        AllowOverride All
        Order Allow,Deny
        Allow from All
    </Directory>

    ErrorLog /var/log/apache2/pdfraktor_error.log
    CustomLog /var/log/apache2/pdfraktor_access.log combined
</VirtualHost>