version: "3.5"

services:
  web:
    image: pdfraktor
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ".:/var/www/project"
      - ".docker/vhosts:/etc/apache2/sites-enabled"
    ports:
      - 7777:80
      - 8888:8000
    depends_on:
      - database
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: pdfraktor
      MYSQL_ROOT_PASSWORD: demo